CREATE DATABASE faculdade_fecaf;
USE faculdade_fecaf;
CREATE TABLE ALUNOS (
    ID_Aluno INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    Cpf VARCHAR(11) NOT NULL UNIQUE,
    Data_nascimento DATE NOT NULL
);  
CREATE TABLE TELEFONES_ALUNOS(
    ID_Telefone INT AUTO_INCREMENT PRIMARY KEY,
    Telefone VARCHAR(15),
    ID_Aluno INT NOT NULL,
    FOREIGN KEY (ID_Aluno) REFERENCES ALUNOS(ID_Aluno) ON DELETE CASCADE 
    );
    
CREATE TABLE EMAIL_ALUNOS(
    ID_Email INT AUTO_INCREMENT PRIMARY KEY,
    Email VARCHAR(255) UNIQUE,
    ID_Aluno INT NOT NULL,
    FOREIGN KEY (ID_Aluno) REFERENCES ALUNOS(ID_Aluno) ON DELETE CASCADE
    );
    
CREATE TABLE ENDERECOS_ALUNOS(
    ID_ENDERECO INT AUTO_INCREMENT PRIMARY KEY,
    Endereco_completo VARCHAR(255),
    Cep VARCHAR(45)NOT NULL,
    Bairro VARCHAR(45)NOT NULL,
    Cidade VARCHAR(45)NOT NULL,
    Estado VARCHAR(45)NOT NULL,
    Pais VARCHAR(45)NOT NULL,
    ID_Aluno INT NOT NULL,
    FOREIGN KEY (ID_Aluno) REFERENCES ALUNOS(ID_Aluno) ON DELETE CASCADE
    );
    
    
CREATE TABLE PROFESSORES (
    ID_Professor INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    Cpf VARCHAR(11) NOT NULL UNIQUE,
    Especializacao VARCHAR(100),
    Telefone VARCHAR(15)
);
CREATE TABLE TELEFONES_PROF(
    ID_Telefone INT AUTO_INCREMENT PRIMARY KEY,
    Numero VARCHAR(15),
	ID_Professor INT NOT NULL,
    FOREIGN KEY (ID_Professor) REFERENCES PROFESSORES(ID_Professor) ON DELETE CASCADE
);
CREATE TABLE ESPECIALIZACAO_PROF(
    ID_Especializacao INT AUTO_INCREMENT PRIMARY KEY,
    Especializacao VARCHAR(45),
    ID_Professor INT NOT NULL,
    FOREIGN KEY (ID_Professor) REFERENCES PROFESSORES(ID_Professor) ON DELETE CASCADE
);

CREATE TABLE CURSOS (
    ID_Curso INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    Duracao_semestres INT NOT NULL
);


CREATE TABLE DISCIPLINAS (
    iD_Disciplina INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    Carga_horaria INT NOT NULL,
    ID_Curso INT NOT NULL,
    FOREIGN KEY (ID_Curso) REFERENCES CURSOS(ID_Curso) ON DELETE CASCADE
);


CREATE TABLE TURMAS (
    ID_Turma INT AUTO_INCREMENT PRIMARY KEY,
    ID_Disciplina INT NOT NULL,
    ID_Professor INT NOT NULL,
    semestre VARCHAR(6) NOT NULL, 
    FOREIGN KEY (ID_Disciplina) REFERENCES DISCIPLINAS(ID_Disciplina) ON DELETE CASCADE,
    FOREIGN KEY (ID_Professor) REFERENCES PROFESSORES(ID_Professor) ON DELETE CASCADE
);


CREATE TABLE MATRICULAS (
    ID_Matricula INT AUTO_INCREMENT PRIMARY KEY,
    ID_Turma INT NOT NULL,
    ID_Aluno INT NOT NULL,
    FOREIGN KEY (ID_Turma) REFERENCES TURMAS(ID_Turma) ON DELETE CASCADE,
    FOREIGN KEY (ID_Aluno) REFERENCES ALUNOS(ID_Aluno) ON DELETE CASCADE
);


CREATE TABLE NOTAS (
    ID_Nota INT AUTO_INCREMENT PRIMARY KEY,
    ID_Matricula INT NOT NULL,
    Avaliacao VARCHAR(50) NOT NULL, 
    Nota DECIMAL(5,2) NOT NULL,
    FOREIGN KEY (ID_Matricula) REFERENCES MATRICULAS(ID_Matricula) ON DELETE CASCADE
);
